language: python
python:
- 3.7
install:
- pip install -r requirements.txt
- pip install codacy-coverage
script:
- cd Citra
- cp travis_local_settings.py local_settings.py
deploy:
  buildpack: python
  provider: heroku
  app: citra-ispp
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
  on:
    branch: deploy/s1
