# Generated by Django 3.1.4 on 2021-03-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shop'),
        ),
    ]
