# Generated by Django 3.1.3 on 2021-05-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210429_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.FloatField(),
        ),
    ]
