# Generated by Django 3.1.3 on 2021-04-19 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210418_1755'),
    ]
