# Generated by Django 3.1.3 on 2021-05-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210503_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.FloatField(),
        ),
    ]
