# Generated by Django 3.1.3 on 2021-03-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210321_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
