# Generated by Django 3.1.4 on 2021-05-12 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210503_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forummessage',
            name='text',
            field=models.TextField(max_length=120),
        ),
    ]
