# Generated by Django 3.1.3 on 2021-03-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210326_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isAccepted',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.customuser'),
            preserve_default=False,
        ),
    ]
