# Generated by Django 3.1.3 on 2021-04-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chatmessage_date'),
        ('main', '0006_auto_20210327_1133'),
    ]

    operations = [
    ]
