# Generated by Django 3.1.4 on 2021-04-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20210404_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
