# Generated by Django 3.1.3 on 2021-04-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210416_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.TextField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.TextField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
